---
title: "Exercise #3"
subtitle: "Fortgeschrittene Statistische Software für NF"
author: "Diana Korchmar (12362412)"
date: "`r Sys.Date()`"
output: distill::distill_article
---

## Exercise 1: Initializing git (4 Points)

a)  Start by initializing a new R project with git support, called
    `2024-exeRcise-sheet-3`. 
    
b)  Commit the files generated by Rstudio.

c)  For all of the following tasks in this exercise sheet we ask you to
    always commit your changes after finishing each subtask e.g. create
    a commit after task *1d*, *1e* etc.

d)  Name 2 strengths and 2 weaknesses of git. (Don't forget to create a
    commit after this answer, see *1c*)
    
    **Strengths**

    • Very hard to lose files with git

    • History allows you to go back and understand change

    **Weaknesses**

    • Can be a bit complicated to use (esp. at first)

    • History takes up file space (only little)
    
e)  Knit this exercise sheet. Some new files will automatically be
    generated when knitting the sheet e.g. the HTML page. Ignore these
    files, as we only want to track the source files themselves.

## Exercise 2: Putting your Repository on GitHub (3.5 Points)

a)  Create a new repository on GitHub in your account named
    `exeRcise-sheet-3`. Make sure you create a **public repository** so
    we are able to see it for grading. Add the link to the repository
    below:
    
    https://github.com/dikorchmar/exeRcise-sheet-3
    
b)  Push your code to this new repository by copying and executing the
    snippet on github listed under
    `…or push an existing repository from the command line`.
    
c)  Regularly push your latest changes to GitHub again and especially do
    so when you are finished with this sheet.

## Exercise 3: Baby-Names in Munich (3.5 Points)

a)  Download the data for both years and track it in git. For small
    datasets like these adding them to git is not a problem.

b)  Load the data for both years into R. Check the type of the count
    variable ("Anzahl") and look into the data to determine why it is
    not numeric? Fix the problem in an appropriate manner, it is OK if
    some of the counts are inaccurate because of this. Explain your
    solution and the repercussions.

c)  Calculate the total number of babies born in Munich in 2022
    and 2023. Which year had the bigger baby-boom?

d)  Add a new column `year` to both datasets which holds the correct
    year for each.

e)  Combine both datasets into one using `bind_rows()`.

f)  Combine the counts for same names to determine the most popular
    names across both years. Print out the top 10 names in a nicely
    formatted table for both years. Include a table caption.

## Exercise 4: Open Analysis (4 points)

a)  Go to <https://github.com/owid/owid-datasets/tree/master/datasets>
    and choose a dataset that interests you. You can have a look at
    <https://ourworldindata.org/> to gather some inspiration.
    
b)  Download the dataset and track it in git.

c)  Put the name / title of the dataset and a link to it below.

-   Dataset Name: ...
-   Link: <https://github.com/owid/owid-datasets/>...

d)  Come up with a (research) question you want to answer with the data
    and briefly explain why you believe this is an interesting question
    within one sentence. It should be a question that can be answered
    with the dataset and using R.
    
e)  Use R to answer your chosen question.

f)  Create a meaningful plot / figure with the dataset. Make sure to
    provide a figure caption (via the chunk options / Rmarkdown) and
    correctly label the figure.

